quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/my_db_movie
quarkus.datasource.username = phuongahihi
quarkus.datasource.password = 13032004
quarkus.datasource.db-kind = postgresql
quarkus.hibernate-orm.database.generation = drop-and-create